### ISSUE TITLE
Does not support folders

### ISSUE THREAD

**Issue by WallyCZ** [dmex/lxssattr#2]
`lxssattr.exe c:\lxss\home\myhome`
[ERROR] NtOpenFile: 0xc00000ba

**Comment by dmex** [comment]
Thanks! 

The flags for NtCreateFile were incorrect. I've released a newer version if you can give it a try?
https://github.com/dmex/lxssattr/releases/tag/1.2

**Comment by WallyCZ** [comment]
Wow, that was quick. Yep, it works now, thanks!
